/* 
 * Copyright (C) 2016 NexusTools.
 *
 * This library is free software: you can redistribute it and/or modify  
 * it under the terms of the GNU Lesser General Public License as   
 * published by the Free Software Foundation, version 3.0.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package net.nexustools.njs.compiler;

/**
 *
 * @author Katelyn Slater <kate@nexustools.com>
 */
public class SourceBuilder {

    java.lang.String indent = "";
    StringBuilder builder = new StringBuilder();
    int row = 1;

    public int row() {
        return row;
    }

    public void append(java.lang.String source) {
        assert (source.indexOf('\n') == -1);
        builder.append(source);
    }

    public void appendln(java.lang.String source) {
        append(source);
        builder.append('\n');
        builder.append(indent);
        row++;
    }

    public void appendln() {
        builder.append('\n');
        builder.append(indent);
        row++;
    }

    public void indent() {
        indent += '\t';
        if (Character.isWhitespace(builder.charAt(builder.length() - 1))) {
            builder.append('\t');
        }
    }

    public void unindent() {
        int pos = builder.length() - 1;
        indent = indent.substring(0, indent.length() - 1);
        if (Character.isWhitespace(builder.charAt(pos))) {
            builder.deleteCharAt(pos);
        }
    }

    @Override
    public java.lang.String toString() {
        return builder.toString();
    }

    public void appendLicense() {
        appendln("/*");
        appendln(" * Generated by NJS");
        appendln(" * https://nexustools.com/projects/njs");
        appendln(" * ");
        appendln(" * NJS is licensed under the LGPLv3");
        appendln(" * You must use a compatible license");
        appendln(" */");
        appendln();
    }
}
